---
- name: first play
  hosts: nodes
  tasks:
    - name: install tmux
      package:
        name: tmux
        state: present
    
    - name: create an archive
      archive:
        path: /var/log
        dest: /tmp/logs.tar.gz
        format: gz

- name: second play
  hosts: worker
  tasks:
    - name: install git
      package:
        name: git
        state: present
